
// Planet data - real scientific measurements
const PLANETS_DATA = {
    sun: {
        name: "Sun",
        type: "G-type Main-sequence Star",
        diameter: "1,392,700 km",
        diameterKm: 1392700,
        mass: "1.989 × 10³⁰ kg",
        massValue: 1.989e30,
        temperature: "5,500°C",
        temperatureValue: 5500,
        gravity: "274 m/s²",
        gravityValue: 274,
        distance: "0 km",
        distanceValue: 0,
        orbit: "N/A",
        color: 0xFFDD00,
        emissive: 0xFF6600,
        radius: 696340,
        texture: "sun",
        description: "The Sun is the star at the center of our Solar System. It is a nearly perfect sphere of hot plasma, heated to incandescence by nuclear fusion reactions in its core. The Sun accounts for about 99.86% of the total mass of the Solar System.",
        rotationSpeed: 0.001,
        orbitSpeed: 0,
        moons: 0,
        atmosphere: "Hydrogen (73%), Helium (25%)"
    },
    mercury: {
        name: "Mercury",
        type: "Terrestrial Planet",
        diameter: "4,879 km",
        diameterKm: 4879,
        mass: "3.301 × 10²³ kg",
        massValue: 3.301e23,
        temperature: "167°C to 427°C",
        temperatureValue: 350,
        gravity: "3.7 m/s²",
        gravityValue: 3.7,
        distance: "57.9 million km",
        distanceValue: 57900000,
        orbit: "88 days",
        color: 0x888888,
        emissive: 0x444444,
        radius: 2439.5,
        texture: "mercury",
        description: "Mercury is the smallest and innermost planet in the Solar System. It orbits the Sun once every 88 Earth days. Despite being the closest planet to the Sun, it's not the hottest (that's Venus).",
        rotationSpeed: 0.004,
        orbitSpeed: 0.04,
        moons: 0,
        atmosphere: "Thin exosphere"
    },
    venus: {
        name: "Venus",
        type: "Terrestrial Planet",
        diameter: "12,104 km",
        diameterKm: 12104,
        mass: "4.867 × 10²⁴ kg",
        massValue: 4.867e24,
        temperature: "462°C",
        temperatureValue: 462,
        gravity: "8.87 m/s²",
        gravityValue: 8.87,
        distance: "108.2 million km",
        distanceValue: 108200000,
        orbit: "225 days",
        color: 0xFFAA66,
        emissive: 0xCC8855,
        radius: 6052,
        texture: "venus",
        description: "Venus is the second planet from the Sun. It is named after the Roman goddess of love and beauty. Venus is the second-brightest natural object in Earth's night sky after the Moon.",
        rotationSpeed: 0.002,
        orbitSpeed: 0.015,
        moons: 0,
        atmosphere: "96.5% CO₂, 3.5% N₂"
    },
    earth: {
        name: "Earth",
        type: "Terrestrial Planet",
        diameter: "12,742 km",
        diameterKm: 12742,
        mass: "5.972 × 10²⁴ kg",
        massValue: 5.972e24,
        temperature: "14°C (average)",
        temperatureValue: 14,
        gravity: "9.807 m/s²",
        gravityValue: 9.807,
        distance: "149.6 million km",
        distanceValue: 149600000,
        orbit: "365.25 days",
        color: 0x4488FF,
        emissive: 0x224488,
        radius: 6371,
        texture: "earth",
        description: "Earth is the third planet from the Sun and the only astronomical object known to harbor life. About 29% of Earth's surface is land consisting of continents and islands.",
        rotationSpeed: 0.01,
        orbitSpeed: 0.01,
        moons: 1,
        atmosphere: "78% N₂, 21% O₂, 1% Ar"
    },
    mars: {
        name: "Mars",
        type: "Terrestrial Planet",
        diameter: "6,779 km",
        diameterKm: 6779,
        mass: "6.417 × 10²³ kg",
        massValue: 6.417e23,
        temperature: "-63°C (average)",
        temperatureValue: -63,
        gravity: "3.721 m/s²",
        gravityValue: 3.721,
        distance: "227.9 million km",
        distanceValue: 227900000,
        orbit: "687 days",
        color: 0xFF6666,
        emissive: 0xCC5555,
        radius: 3389.5,
        texture: "mars",
        description: "Mars is the fourth planet from the Sun and the second-smallest planet in the Solar System. Often called the 'Red Planet' due to iron oxide prevalent on its surface.",
        rotationSpeed: 0.008,
        orbitSpeed: 0.008,
        moons: 2,
        atmosphere: "95% CO₂, 2.7% N₂, 1.6% Ar"
    },
    jupiter: {
        name: "Jupiter",
        type: "Gas Giant",
        diameter: "139,820 km",
        diameterKm: 139820,
        mass: "1.898 × 10²⁷ kg",
        massValue: 1.898e27,
        temperature: "-108°C",
        temperatureValue: -108,
        gravity: "24.79 m/s²",
        gravityValue: 24.79,
        distance: "778.5 million km",
        distanceValue: 778500000,
        orbit: "11.86 years",
        color: 0xFFCC99,
        emissive: 0xCCAA77,
        radius: 69911,
        texture: "jupiter",
        description: "Jupiter is the fifth planet from the Sun and the largest in the Solar System. It is a gas giant with a mass one-thousandth that of the Sun, but two-and-a-half times that of all the other planets combined.",
        rotationSpeed: 0.02,
        orbitSpeed: 0.002,
        moons: 79,
        atmosphere: "90% H₂, 10% He"
    },
    saturn: {
        name: "Saturn",
        type: "Gas Giant",
        diameter: "116,460 km",
        diameterKm: 116460,
        mass: "5.683 × 10²⁶ kg",
        massValue: 5.683e26,
        temperature: "-139°C",
        temperatureValue: -139,
        gravity: "10.44 m/s²",
        gravityValue: 10.44,
        distance: "1.434 billion km",
        distanceValue: 1434000000,
        orbit: "29.46 years",
        color: 0xFFDD88,
        emissive: 0xCCBB66,
        radius: 58232,
        texture: "saturn",
        description: "Saturn is the sixth planet from the Sun and the second-largest in the Solar System, after Jupiter. It is a gas giant with an average radius about nine times that of Earth.",
        rotationSpeed: 0.018,
        orbitSpeed: 0.001,
        moons: 82,
        atmosphere: "96% H₂, 3% He"
    },
    uranus: {
        name: "Uranus",
        type: "Ice Giant",
        diameter: "50,724 km",
        diameterKm: 50724,
        mass: "8.681 × 10²⁵ kg",
        massValue: 8.681e25,
        temperature: "-197°C",
        temperatureValue: -197,
        gravity: "8.69 m/s²",
        gravityValue: 8.69,
        distance: "2.871 billion km",
        distanceValue: 2871000000,
        orbit: "84.01 years",
        color: 0x66CCFF,
        emissive: 0x4488CC,
        radius: 25362,
        texture: "uranus",
        description: "Uranus is the seventh planet from the Sun. It has the third-largest planetary radius and fourth-largest planetary mass in the Solar System. Uranus is similar in composition to Neptune.",
        rotationSpeed: 0.015,
        orbitSpeed: 0.0007,
        moons: 27,
        atmosphere: "83% H₂, 15% He, 2% CH₄"
    },
    neptune: {
        name: "Neptune",
        type: "Ice Giant",
        diameter: "49,244 km",
        diameterKm: 49244,
        mass: "1.024 × 10²⁶ kg",
        massValue: 1.024e26,
        temperature: "-201°C",
        temperatureValue: -201,
        gravity: "11.15 m/s²",
        gravityValue: 11.15,
        distance: "4.495 billion km",
        distanceValue: 4495000000,
        orbit: "164.8 years",
        color: 0x4466FF,
        emissive: 0x2244AA,
        radius: 24622,
        texture: "neptune",
        description: "Neptune is the eighth and farthest known Solar planet from the Sun. It is the fourth-largest planet by diameter, the third-most-massive planet, and the densest giant planet.",
        rotationSpeed: 0.012,
        orbitSpeed: 0.0004,
        moons: 14,
        atmosphere: "80% H₂, 19% He, 1% CH₄"
    }
};

// Solar System configuration (relative sizes and distances for visualization)
const SOLAR_SYSTEM_CONFIG = {
    scale: 1 / 1000000, // Scale down for visualization
    distanceScale: 1 / 10000000,
    orbitSpeeds: {
        mercury: 4.14,
        venus: 1.62,
        earth: 1,
        mars: 0.53,
        jupiter: 0.084,
        saturn: 0.034,
        uranus: 0.012,
        neptune: 0.006
    }
};

// Star field data
const STAR_DATA = {
    count: 250000,
    size: 2,
    colorRange: [
        {color: 0xFFFFFF, intensity: 1.0}, // White stars
        {color: 0x4CC9F0, intensity: 0.8}, // Blue stars
        {color: 0xFFAA66, intensity: 0.7}, // Orange stars
        {color: 0xFF6666, intensity: 0.6}  // Red stars
    ]
};

// Real-time explorer data (simulated)
const EXPLORERS_DATA = [
    {id: 1, name: "Astro_John", location: "Near Earth", distance: 384400},
    {id: 2, name: "Cosmic_Jane", location: "Mars Orbit", distance: 225000000},
    {id: 3, name: "Star_Seeker", location: "Jupiter's Moons", distance: 628700000},
    {id: 4, name: "Galaxy_Rider", location: "Asteroid Belt", distance: 329000000},
    {id: 5, name: "Quantum_Traveler", location: "Near Saturn", distance: 1275000000},
    {id: 6, name: "Space_Pioneer", location: "Solar North Pole", distance: 695500}
];

// Constellation data
const CONSTELLATIONS = [
    {name: "Orion", stars: [[0,0,0], [100,50,0], [150,100,0], [50,150,0]]},
    {name: "Ursa Major", stars: [[-200,100,0], [-180,120,0], [-150,140,0], [-120,130,0]]}
];
